### PR TITLE
Fixes (issue #11)

### LINKED ISSUE #11: Steps out of order bug - ice gloves in inv but telling me to withdraw
If you log out after withdrawing ore but before putting it on the conveyor, log back in, when you attempt a new cycle it will be out of order, prompting you to withdraw your ice gloves when they are in your inventory next time you visit the bank to drop off your bars, and everytime after that. reinstalling does not fix this issue
image

### PR DESCRIPTION
**Pull request by hugocowan**
Fix issue #11 and set max coal in inventory to 27 when gold smithing with cape.

closes #11

### CODE REVIEW

**Comment by hugocowan** [comment]
@Toofifty This fixes the bug in issue #11. I've tested the fix myself - it's a very simple error from my earlier PR.

I also fixed a separate, more niche bug, also from my earlier PR.

**Comment by hugocowan** [comment]
@Toofifty Hope you're back soon my guy. Sorry for sneaking a bug in while you're on holiday. I've made a different PR including tests for every method so stuff like this is much, much less likely to happen in the future. That one is definitely secondary to this PR though.

**Comment by Toofifty** [comment]
@hugocowan Sorry! I got back a few days ago, just haven't checked in here yet 😅 

This one looks good - I'll push it to plugin hub soon. I can't believe you added tests too 🤯

**Comment by hugocowan** [comment]
> @hugocowan Sorry! I got back a few days ago, just haven't checked in here yet 😅
> 
> This one looks good - I'll push it to plugin hub soon. I can't believe you added tests too 🤯

I uhh.. I may have a few other PRs lined up after these. 👀

**Pull request merged**
